_wandb:
    value:
        cli_version: 0.23.1
        e:
            78iql0feklsu0k7bioo9pm1dzhtl27yn:
                apple:
                    ecpuCores: 4
                    gpuCores: 40
                    memoryGb: 128
                    name: Apple M3 Max
                    pcpuCores: 12
                    ramTotalBytes: "137438953472"
                    swapTotalBytes: "16106127360"
                codePath: /Users/silen/Desktop/Learning/silen-ai/projects/transformer/transformer.ipynb
                codePathLocal: transformer.ipynb
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1995218165760"
                        used: "1029865738240"
                email: silen.naihin@gmail.com
                executable: /Users/silen/anaconda3/bin/python
                git:
                    commit: 61a144a5418e9760943c053394d87e1a1fff91b6
                    remote: https://github.com/SilenNaihin/silen-ai.git
                host: MacBook-Pro-79.local
                memory:
                    total: "137438953472"
                os: macOS-14.1-arm64-arm-64bit
                program: /Users/silen/Desktop/Learning/silen-ai/projects/transformer/transformer.ipynb
                python: CPython 3.11.5
                root: /Users/silen/Desktop/Learning/silen-ai/projects/transformer
                startedAt: "2025-12-27T04:34:40.188481Z"
                writerId: 78iql0feklsu0k7bioo9pm1dzhtl27yn
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
            "3":
                - 2
                - 16
            "4": 3.11.5
            "5": 0.23.1
            "6": 4.57.3
            "8":
                - 1
                - 2
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 10
lr:
    value: 0.001
max_steps_per_epoch:
    value: 500
table_log_freq:
    value: 200
text_sample_freq:
    value: 20
wandb_name:
    value: null
wandb_project:
    value: day1-demotransformer
weight_decay:
    value: 0.01
